-- MySQL Script generated by MySQL Workbench
-- Thu Feb  1 13:47:49 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema boutique
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema boutique
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `boutique` ;
USE `boutique` ;

-- -----------------------------------------------------
-- Table `boutique`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique`.`Categories` (
                                                       `id` INT NOT NULL AUTO_INCREMENT,
                                                       `name` VARCHAR(45) NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boutique`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique`.`Products` (
                                                     `id` INT NOT NULL AUTO_INCREMENT,
                                                     `title` VARCHAR(45) NULL,
    `description` VARCHAR(45) NULL,
    `priceWT` DECIMAL(9,2) NULL,
    `weight` DECIMAL(9,2) NULL,
    `TVA` DECIMAL(9,2) NULL,
    `stock` INT NULL,
    `Categories_id` INT NOT NULL,
    `priceTTC` DECIMAL(9,2) NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_Products_Categories1_idx` (`Categories_id` ASC) VISIBLE,
    CONSTRAINT `fk_Products_Categories1`
    FOREIGN KEY (`Categories_id`)
    REFERENCES `boutique`.`Categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boutique`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique`.`Client` (
                                                   `id` INT NOT NULL AUTO_INCREMENT,
                                                   `name` VARCHAR(45) NULL,
    `surname` VARCHAR(45) NULL,
    `email` VARCHAR(45) NULL,
    `password` VARCHAR(45) NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boutique`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique`.`Order` (
                                                  `id` INT NOT NULL AUTO_INCREMENT,
                                                  `orderDate` DATE NULL,
                                                  `deliveryDate` DATE NULL,
                                                  `Client_id` INT NOT NULL,
                                                  PRIMARY KEY (`id`, `Client_id`),
    INDEX `fk_Order_Client1_idx` (`Client_id` ASC) VISIBLE,
    CONSTRAINT `fk_Order_Client1`
    FOREIGN KEY (`Client_id`)
    REFERENCES `boutique`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boutique`.`Products_has_Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique`.`Products_has_Order` (
                                                               `Produits_id` INT NOT NULL,
                                                               `Order_id` INT NOT NULL,
                                                               `quantity` INT NULL,
                                                               PRIMARY KEY (`Produits_id`, `Order_id`),
    INDEX `fk_Produits_has_Order_Order1_idx` (`Order_id` ASC) VISIBLE,
    INDEX `fk_Produits_has_Order_Produits_idx` (`Produits_id` ASC) VISIBLE,
    CONSTRAINT `fk_Produits_has_Order_Produits`
    FOREIGN KEY (`Produits_id`)
    REFERENCES `boutique`.`Products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Produits_has_Order_Order1`
    FOREIGN KEY (`Order_id`)
    REFERENCES `boutique`.`Order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
