-- MySQL Script generated by MySQL Workbench
-- Thu Feb  1 11:05:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop` ;
USE `shop` ;

-- -----------------------------------------------------
-- Table `shop`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`categories` (
                                                   `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                   `name` VARCHAR(45) NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`products` (
                                                 `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                 `name` VARCHAR(50) NOT NULL,
    `description` TEXT(500) NULL,
    `priceWithoutTax` DECIMAL(9,2) NOT NULL,
    `VAT` DECIMAL(9,2) NOT NULL,
    `weight` DECIMAL(6,3) NOT NULL,
    `stock` INT NULL DEFAULT 0,
    `categories_id` INT UNSIGNED NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_products_categories`
    FOREIGN KEY (`categories_id`)
    REFERENCES `shop`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `shop`.`products` (`name` ASC) VISIBLE;

CREATE INDEX `fk_products_categories_idx` ON `shop`.`products` (`categories_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `shop`.`costumers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`costumers` (
                                                  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                  `lastName` VARCHAR(45) NULL,
    `firstName` VARCHAR(45) NULL,
    `email` VARCHAR(100) NOT NULL,
    `password` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `shop`.`costumers` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `shop`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`orders` (
                                               `id` INT NOT NULL AUTO_INCREMENT,
                                               `registrationDate` DATE NOT NULL,
                                               `deliverydate` DATE NOT NULL,
                                               `costumers_id` INT UNSIGNED NOT NULL,
                                               PRIMARY KEY (`id`, `costumers_id`),
    CONSTRAINT `fk_orders_costumers1`
    FOREIGN KEY (`costumers_id`)
    REFERENCES `shop`.`costumers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE INDEX `fk_orders_costumers1_idx` ON `shop`.`orders` (`costumers_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `shop`.`products_has_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`products_has_orders` (
                                                            `products_id` INT UNSIGNED NOT NULL,
                                                            `orders_id` INT NOT NULL,
                                                            `orders_costumers_id` INT UNSIGNED NOT NULL,
                                                            `quantity` INT NULL,
                                                            PRIMARY KEY (`products_id`, `orders_id`, `orders_costumers_id`),
    CONSTRAINT `fk_products_has_orders_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `shop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_products_has_orders_orders1`
    FOREIGN KEY (`orders_id` , `orders_costumers_id`)
    REFERENCES `shop`.`orders` (`id` , `costumers_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

CREATE INDEX `fk_products_has_orders_orders1_idx` ON `shop`.`products_has_orders` (`orders_id` ASC, `orders_costumers_id` ASC) VISIBLE;

CREATE INDEX `fk_products_has_orders_products1_idx` ON `shop`.`products_has_orders` (`products_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
